### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by BakingBrains** [ShaneRun/multistream-CNN#1]
Traceback (most recent call last):
File "/home/acharyaece/PycharmProjects/Speaker_recog/multistream-CNN/trainer/trainSpeakerNet.py", line 161, in
trainLoader = DatasetLoader(args.train_list, **vars(args))
File "/home/acharyaece/PycharmProjects/Speaker_recog/multistream-CNN/trainer/DatasetLoader.py", line 75, in init
speaker_name = data[0];
IndexError: list index out of range

any suggestion??

**Comment by BakingBrains** [comment]
resolved
